### PR TITLE
Add Markdown format

### LINKED ISSUE #675: Markdown Table Output Support
**What would you like to be added**: Add support for markdown tables to be an output format.

**Why is this needed**: Would allow for easier automated self-documentation without having to rely on external tooling to manipulate the outputs.

**Additional context**:
The format would behavior similarly to these applications output functionality. 

https://github.com/terraform-docs/terraform-docs
https://github.com/norwoodj/helm-docs

### PR DESCRIPTION
**Pull request by Dariusch**
This PullRequest is basically adding a markdown option as an output format and closes #675

### CODE REVIEW

**Comment by spiffcs** [comment]
awesome addition @Dariusch! I'll approve this and get it merged. 

If there are more fields, extensions, or updates that we want to see for this format I think they can be follow-ups to this.

cc @Btodhunter regarding if the github token needs updated permissions for the `Add pr to OSS project` action.

**Comment by spiffcs** [comment]
Hey @Dariusch!

Just a quick update here - I talked about this with @wagoodman and it looks like we're leaning more towards getting generic template presenters added into syft in the same way grype handles them:

https://github.com/anchore/grype#using-templates

Templates in this case can then be used to generate an infinitely flexible version of a markdown document rather than just iterating on a single fixed case. 

I apologize for the miscue on this PR - what I can do it take the initial work you've put in here branch it and put you as co-author when we bring in the template work for Syft if that sounds like a good plan?

**Comment by Dariusch** [comment]
@spiffcs no problem at all, I was just happy to help out with a contribution.

I will close this PR for now and wait for the templates 😄

**Comment by luhring** [comment]
Just a heads up, we're going to prioritize the templating support for Syft (which had been created as [this issue](https://github.com/anchore/syft/issues/152) a while back), which should work just like Grype's templating support. I've asked @jonasagx to look into this functionality.

**Pull request closed without merging**
