### PR TITLE
Fix #1245 Update SPDX license list to 3.18

### LINKED ISSUE #1245: Update SPDX license list to 3.18
**What happened**:

FIle
```
internal/spdxlicense/generate/test-fixtures/licenses.json
```
has ```"licenseListVersion": "3.17"```

**What you expected to happen**:

https://spdx.org/licenses/ is now at 3.18
```
internal/spdxlicense/generate/test-fixtures/licenses.json
```
should be updated.

### PR DESCRIPTION
**Pull request by vargenau**
File licenses.json taken from https://github.com/spdx/license-list-data/releases/tag/v3.18

Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>

Fixes: #1245

### CODE REVIEW

**Comment by kzantow** [comment]
Hi @vargenau -- I ran the tests locally it looks like unit tests are failing here (I suspect CI will tell us the same), could you have a look?

**Comment by kzantow** [comment]
A quick note: this change to the test fixture has seemed to break the tests, which were previously working with the existing fixture. I think this may not be needed?

**Comment by vargenau** [comment]
> Hi @vargenau -- I ran the tests locally it looks like unit tests are failing here (I suspect CI will tell us the same), could you have a look?

Hi @kzantow,

I have fixed the unit test that was failing. It should be OK now.

**Comment by kzantow** [comment]
@vargenau I don't see any new commits here, was there something you meant to push?

**Comment by kzantow** [comment]
Hi @vargenau -- it looks like the unit tests are still failing. If you'd like to run them locally, assuming you have Docker installed and running you can run `make unit` in order to make sure your changes are going to work.

**Comment by vargenau** [comment]
> Hi @vargenau -- it looks like the unit tests are still failing. If you'd like to run them locally, assuming you have Docker installed and running you can run `make unit` in order to make sure your changes are going to work.

Hi @kzantow 

I have fixed the tests. Sorry, but I still have issues running the tests locally, I have an error in downloading a file.

**Review by spiffcs — APPROVED** [review]

**Pull request merged**
