### PR TITLE
Add haskell binaries cataloger

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Build failing seem to be because of space issue on the runner

**Comment by LaurentGoderre** [comment]
@spiffcs could I get a review for this?

**Comment by spiffcs** [comment]
Thanks for the Tag! I'll put this on my this for before lunch

**Review by spiffcs — APPROVED** [review]

**Comment by spiffcs** [comment]
Quick and easy - thanks for adding the snippets and classifiers for these items

**Pull request merged**
