### PR TITLE
chore(reproducibility): add buildid= and trimpath

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

### CODE REVIEW

**Comment by developer-guy** [comment]
cc: @wagoodman

**Comment by wagoodman** [comment]
The `trimpath` and `buildid` changes look great 👍 , but same question as https://github.com/anchore/grype/pull/642#issuecomment-1050014381 , why change `GOPATH` here?

**Review by wagoodman — CHANGES_REQUESTED** [review]
See https://github.com/anchore/grype/pull/642#pullrequestreview-893111730

**Comment by developer-guy** [comment]
seems everything is fine @wagoodman, thanks a ton 🙋🏻‍♂️

**Review by spiffcs — DISMISSED** [review]

**Comment by wagoodman** [comment]
I'm going to mark this as stale, but feel free to open up a new issue if you wanted to talk about this further!

**Pull request closed without merging**
