### PR TITLE
Added binary classifier for GCC

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Review by kzantow — APPROVED** [review]
If you would be able to [add a `config.yaml` entry](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/binary/test-fixtures/config.yaml#L12) for an image where the binary originated, that would be much appreciated!

**Comment by LaurentGoderre** [comment]
Note to self:

```
gcc:12.3.0-bookworm:sha256:2e3c00752fa23a0993b6618760bbc20263b272a0b34b2d4883159e3ebba9d8b6
```

**Comment by LaurentGoderre** [comment]
Done!

**Review by kzantow — APPROVED** [review]

**Comment by kzantow** [comment]
Thanks @LaurentGoderre !

**Pull request merged**
