### PR TITLE
Bump the golang.org/x/exp dependency and fix a build breakage.

### PR DESCRIPTION
**Pull request by dlorenc**
This was causing a conflict for us in some code that imports syft.

### CODE REVIEW

**Comment by spiffcs** [comment]
Thanks @dlorenc! Let me get the conflicts resolved here and I'll try and have this merged and ready for the next release ASAP

**Comment by spiffcs** [comment]
Just a quick note on this PR - after we update the CI files with the correct Go version we'll still need to check current consumers of syft within our own tooling and what they look like when upgraded to `v1.21` if there are no issues then we can start upgrading each consumer to use `v1.21`. Then we can merge this PR into Syft. 

Thanks again for the contribution/fix!

**Comment by spiffcs** [comment]
related PR - https://github.com/anchore/syft/pull/2067

**Comment by dlorenc** [comment]
Ah whoops - I actually didn't intend for go to add the 1.21 stuff, that was a side effect of me using 1.21 to perform the change myself I think. Feel free to separate that part out if that helps.

**Comment by spiffcs** [comment]
No worries - so far it's not too big of a lift. If I run into complications I'll be sure to separate this out as it's own separate thing to make sure it get's resolved and is not blocked by the update

**Review by spiffcs — APPROVED** [review]

**Pull request merged**
