### PR TITLE
add metadata filed on pod usage template

### PR DESCRIPTION
**Pull request by majinghe**
add metadata filed on pod usage template to make sure the yaml file can be applied succ.

### CODE REVIEW

**Comment by majinghe** [comment]
corresponding issue is https://github.com/anchore/syft/issues/787

**Comment by spiffcs** [comment]
Thanks @majinghe for the quick contribution here!

I've kicked off the CI and will get this added into the README.

**Review by spiffcs — APPROVED** [review]

**Comment by spiffcs** [comment]
@majinghe - Would you be able to sign and verify the commit as documented [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

**Comment by majinghe** [comment]
@spiffcs  i have signed and re-committed again, pls approve to run the workflow. Thanks very much.

**Pull request merged**
