### PR TITLE
chore: claim artifacthub package ownership from developer-guy

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

cc: @wagoodman

### CODE REVIEW

**Comment by developer-guy** [comment]
Last but not least, we need to push this file to the OCI registry along with the image itself :point_down: 

https://artifacthub.io/docs/topics/repositories/#repository-metadata

```shell
$ printf "{}" > config.json
$ oras push index.docker.io/anchore/syft:artifacthub.io \
      --manifest-config config.json:application/vnd.cncf.artifacthub.config.v1+yaml \ 
      artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml
```

> to install ORAS CLI: https://oras.land/cli/

**Comment by wagoodman** [comment]
Thanks @developer-guy  I'll push up the existing artifacthub-repo.yaml --I'll hold off on adding the repository ID (for publisher verification) until we get this transferred 👍

**Comment by spiffcs** [comment]
@wagoodman was this ever transfered?

**Review by wagoodman — APPROVED** [review]
The transfer isn't working yet, but I'll merge this for now and try to transfer again

**Pull request merged**
