### PR TITLE
Add version to logs

### LINKED ISSUE #664: Syft verbose log version
**What would you like to be added**:
Verbose logs expose Syft's version

**Why is this needed**:
Whenever a problem happens it is important to have context to reproduce it and knowing the running version is the first step. CI platforms require extra steps to reproduce fails, and environments can change between executions. A log line with version makes it clear

**Additional context**:

### PR DESCRIPTION
**Pull request by jonasagx**
closes #664

### CODE REVIEW

**Comment by wagoodman** [comment]
Having some fun with this one... how about output similar to:
```
[0000]  INFO syft version: 0.32.0-SNAPSHOT-cdaee9b
[0000] DEBUG   ├── buildDate: 2021-12-14T02:53:03Z
[0000] DEBUG   ├── compiler: gc
[0000] DEBUG   ├── gitCommit: cdaee9b6b1e5dad116893ee53597acfa9e9a0c96
[0000] DEBUG   ├── gitTreeState: dirty
[0000] DEBUG   ├── goVersion: go1.17.3
[0000] DEBUG   ├── platform: darwin/amd64
[0000] DEBUG   └── version: 0.32.0-SNAPSHOT-cdaee9b
[0000] DEBUG no new syft update available

```

Notice the tree info shows up as debug and the top row is info. I mocked up how one way do that here: https://github.com/anchore/syft/commit/c62f3ec127de76a00949dfe9b159dcdde22f9b7e

**Review by luhring — COMMENTED** [review]
This PR includes changes to the directory resolver and adds tests for symlink handling... these appear to be unrelated to logging the version. Could we consider either moving this to a separate PR, or explain the need for this in this PR's description? I'm thinking it'd be good to make it obvious to others why this code is being changed here.

**Comment by jonasagx** [comment]
This probably happened while pulling Syft's changes into my fork :/

The fix AFAIK is blocked until I merge this PR https://github.com/anchore/syft/pull/694

**Comment by luhring** [comment]
> This probably happened while pulling Syft's changes into my fork :/
> 
> The fix AFAIK is blocked until I merge this PR #694

Is it true that the unwanted code is isolated to commit f4e60ec? Could you rebase your branch to drop this commit, leaving just the other commit (cdaee9b)? That way this PR isn't necessarily blocked by other PRs.

**Comment by jonasagx** [comment]
I've made a couple mistakes with the rebase. I recreated the PR via a branch: https://github.com/anchore/syft/pull/715

**Pull request closed without merging**
