### PR TITLE
Exclude devDependencies from package-lock.json parsing

### LINKED ISSUE #2348: Syft outputs devDependencies for package-lock.json files
**What happened**:
When scanning a directory with the following files:
`package.json`

```
{
    "name": "first_app",
    "version": "1.0.0",
    "description": "a first app",
    "main": "index.js",
    "scripts": {
      "test": "testing"
    },
    "author": "",
    "license": "ISC",
    "dependencies": {
    },
    "devDependencies": {
      "async": "^3.2.4"
    }
  }
```

package-lock.json
```
{
    "name": "first_app",
    "version": "1.0.0",
    "lockfileVersion": 3,
    "requires": true,
    "packages": {
      "": {
        "name": "first_app",
        "version": "1.0.0",
        "license": "ISC",
        "devDependencies": {
          "async": "^3.2.4"
        }
      },
      "node_modules/async": {
        "version": "3.2.4",
        "resolved": "https://registry.npmjs.org/async/-/async-3.2.4.tgz",
        "integrity": "sha512-iAB+JbDEGXhyIUavoDl9WP/Jj106Kz9DEn1DPgYw5ruDn0e3Wgi3sKFm55sASdGBNOQB8F59d9qQ7deqrHA8wQ==",
        "dev": true
      }
    }
  }
```

It outputs

```
 ✔ Indexed file system                                                                                                                                                                                            tests/data/js_dependencies
 ✔ Cataloged packages              [2 packages]
[0000]  WARN no explicit name and version provided for directory source, deriving artifact ID from the given path (which is not ideal)
NAME       VERSION  TYPE
async      3.2.4    npm
first_app  1.0.0    npm
```

with the `async` devDependency.

**What you expected to happen**:

Syft do not output dev-dependencies as it's done when scanning a `Pipfile.lock`.

**Steps to reproduce the issue**:

Run syft on a directory containing the above file.

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:

````
$ syft version
Application: syft
Version:    0.97.1
BuildDate:  2023-11-17T20:53:01Z
GitCommit:  Homebrew
GitDescription: [not provided]
Platform:   darwin/arm64
GoVersion:  go1.21.4
Compiler:   gc
````

- OS (e.g: `cat /etc/os-release` or similar):

````
$ sw_vers
ProductName:		macOS
ProductVersion:		14.1.1
BuildVersion:		23B81
````

### PR DESCRIPTION
**Pull request by njv299**
# Description

This updates the Javascript cataloger so that packages that are only present as dev dependencies found in `package-lock.json` files are ignored and not included in the resulting SBOM. This behavior more closely aligns with that of other similar catalogers, such as the Python Pipfile.lock parser.

This change supports all current `package-lock.json` schema versions (`1`, `2`, and `3`) in accordance with the spec found [here](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json).

- Fixes #2348 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] I have added unit tests that cover changed behavior
- [X] I have tested my code in common scenarios and confirmed there are no regressions
- [X] I have added comments to my code, particularly in hard-to-understand sections

### CODE REVIEW

**Review by wagoodman — APPROVED** [review]

**Comment by njv299** [comment]
@joaquinricci I would certainly be in support of a `--include-dev-deps` configuration option, but I would argue that that should be an option that is consistently applied across all catalogers (or made available as a configurable option for all relevant catalogers). As of right now, there is different behavior across catalogers with respect to dev dependencies: `Pipfile.lock` file parsing does not include dev deps, `package.json` also doesn't include them, while `package-lock.json` parsing does. 

It's obviously not my decision to make, but in the near-term my opinion is that this PR makes the behavior more consistent as-is and there should be follow-on issues and PRs to holistically add a consistent, comprehensive set of `--include-dev-deps` functionality.

**Comment by kzantow** [comment]
For what it's worth, I agree with all of the comments here: @joaquinricci and @njv299 that this probably should be configurable as part of this PR, the configuration should be applied consistently across pertinent catalogers, and _also_ agree that the default behavior should be to _exclude_ development-only time dependencies.

This is absolutely something that other ecosystems would benefit from: [Java, for example, should probably exclude `test`-scoped dependencies by default](https://github.com/anchore/syft/issues/3130). I think it would be worth spending a little time thinking about how configuration should work. It may be useful to move this discussion to Discourse (there is [a related topic](https://anchorecommunity.discourse.group/t/syft-own-format-how-to-distinguish-dependency-vs-devdependency-for-npm/151)).

**Comment by njv299** [comment]
To clarify my stance on this: In my opinion this PR should be merged as-is. Based on the discussion in the relevant [issue](https://github.com/anchore/syft/issues/2348), the user-feedback that devDependencies are _generally_ not preferred to be included, and my own N=1 experience, it seems very valuable to change the default behavior of Syft today to exclude devDependencies. This solves what appears to be a fairly pressing need for a not-insignificant number of people (myself included), and makes the behavior of Syft more consistent across all catalogers.

I am also fully in support of subsequently making this behavior configurable as discussed above. Personally, though, I think this should be done via follow-on PRs so that the advantages mentioned above can be realized as soon as possible. If time permits I will be happy to help with the implementation of the configuration options, but getting this PR merged and released soon will fix some significant issues in my personal use of Syft.

**Comment by kzantow** [comment]
Hey @njv299 -- I should note, my comments above were not necessarily blockers by any means. However, since there was an ask for making this configurable directly on the PR, would you mind if I pushed a small change to just add the appropriate config/environment variable for the flag so everyone would probably be happy moving this forward?

**Comment by njv299** [comment]
@kzantow Absolutely, that sounds great to me! Thank you!

**Review by wagoodman — APPROVED** [review]

**Comment by kzantow** [comment]
Thanks very much for the contribution, @njv299!

**Pull request merged**
